"""
agents/generator_agent.py

Test Generator Agent
─────────────────────
Reads the parsed test steps (with resolved locators) and generates
a complete, runnable Playwright TypeScript test file (.spec.ts).

Uses Gemini to produce:
  - Playwright Test (@playwright/test) assertions
  - Helper waits for Mendix async Microflows
  - Assertions based on `expected_result`
  - Self-documenting comments linking back to CSV row

Output is written via utils.code_writer.
"""

import os
import re
import json
import logging
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.messages import SystemMessage, HumanMessage
from utils.code_writer import write_test_file

logger = logging.getLogger(__name__)

_LLM: ChatGoogleGenerativeAI | None = None


def _get_llm() -> ChatGoogleGenerativeAI:
    global _LLM
    if _LLM is None:
        _LLM = ChatGoogleGenerativeAI(
            model="gemini-2.0-flash",
            google_api_key=os.getenv("GOOGLE_API_KEY", ""),
            temperature=0,
        )
    return _LLM


# ---------------------------------------------------------------------------
# Step Parser  — converts free-text "steps" column to structured actions
# ---------------------------------------------------------------------------

def parse_steps(raw_steps: str, base_url: str) -> list[dict]:
    """
    Convert a numbered free-text steps string into a list of action dicts.
    Identical to Python version but serves as the source for test body generation.
    """
    steps_raw = re.split(r",\s*\d+\.\s*|\n\s*\d+\.\s*|^\d+\.\s*", raw_steps, flags=re.MULTILINE)
    steps_raw = [s.strip() for s in steps_raw if s.strip()]

    parsed = []
    for raw in steps_raw:
        lower = raw.lower()

        action = "unknown"
        target = ""
        value  = ""

        if re.match(r"navigate|go to|open|visit", lower):
            action = "navigate"
            m = re.search(r"(/\S+)", raw)
            target = m.group(1) if m else base_url

        elif re.match(r"click|press|tap", lower):
            action = "click"
            m = re.search(r"(?:click|press|tap)\s+'?([^']+)'?", raw, re.IGNORECASE)
            target = m.group(1).strip() if m else raw

        elif re.match(r"enter|type|fill|input", lower):
            action = "fill"
            m = re.search(r"'([^']+)'", raw)
            value = m.group(1) if m else ""
            m2 = re.search(r"(?:in|for|into|on)\s+'?([^']+)'?$", raw, re.IGNORECASE)
            target = m2.group(1).strip() if m2 else raw

        elif re.match(r"select|choose", lower):
            action = "select"
            m = re.search(r"'([^']+)'", raw)
            value = m.group(1) if m else ""
            m2 = re.search(r"(?:from|in|on)\s+'?([^']+)'?$", raw, re.IGNORECASE)
            target = m2.group(1).strip() if m2 else raw

        elif re.match(r"assert|verify|check|confirm|see|should", lower):
            action = "assert"
            target = raw

        elif re.match(r"wait", lower):
            action = "wait"
            target = raw

        else:
            action = "click"
            target = raw

        parsed.append({
            "action":  action,
            "target":  target,
            "value":   value,
            "raw":     raw,
            "url":     base_url,
        })

    return parsed


# ---------------------------------------------------------------------------
# Code Generator  — turns resolved steps into Playwright TypeScript code
# ---------------------------------------------------------------------------

MX_PROGRESS_WAIT = (
    "  // Wait for Mendix Microflow/Nanoflow to complete\n"
    "  await page.locator('.mx-progress').waitFor({ state: 'detached', timeout: 30000 });\n"
)

TEST_FILE_TEMPLATE = '''/**
 * Auto-generated by Mendix Playwright Automation Framework
 * Test ID    : {test_id}
 * Test Title : {test_title}
 * CSV Row    : {csv_row_num}
 */

import { test, expect } from '@playwright/test';

const BASE_URL = '{base_url}';

test.describe('{test_title}', () => {{
  test.beforeEach(async ({{ page }}) => {{
    await page.goto(BASE_URL, {{ waitUntil: 'networkidle' }});
    // Wait for Mendix to finish initialising
    await page.locator('.mx-progress').waitFor({{ state: 'detached', timeout: 30000 }});
  }});

  test('{safe_title}', async ({{ page }}) => {{
    /**
     * {test_title}
     * Expected: {expected_result}
     */

{test_body}
  }});
}});
'''


def _generate_step_code(step: dict) -> str:
    """Convert a resolved step dict to one or more lines of TypeScript code."""
    action = step.get("action", "")
    value  = step.get("value", "")
    raw    = step.get("raw", "")
    lr     = step.get("locator_result")

    lines = [f"    // Step: {raw}"]

    if action == "navigate":
        target = step.get("target", "")
        if target.startswith("/"):
            lines.append(f"    await page.goto(`${{BASE_URL}}{target}`, {{ waitUntil: 'networkidle' }});")
            lines.append(f"    await page.locator('.mx-progress').waitFor({{ state: 'detached', timeout: 30000 }});")
        else:
            lines.append(f"    await page.goto('{target}', {{ waitUntil: 'networkidle' }});")
        return "\n".join(lines)

    if action == "assert":
        lines.append(f"    await expect(page).toHaveTitle(new RegExp('{raw}', 'i'));")
        lines.append(f"    // Or: await expect(page.getByText('{raw}')).toBeVisible();")
        return "\n".join(lines)

    if action == "wait" or not lr:
        lines.append(f"    await page.waitForTimeout(1000); // TODO: replace with explicit wait")
        return "\n".join(lines)

    locator_expr = lr["locator"]
    # Convert Python-style get_by_* to camelCase getBy*
    locator_expr = locator_expr.replace("get_by_role", "getByRole")
    locator_expr = locator_expr.replace("get_by_label", "getByLabel")
    locator_expr = locator_expr.replace("get_by_text", "getByText")
    locator_expr = locator_expr.replace("get_by_placeholder", "getByPlaceholder")
    locator_expr = locator_expr.replace("get_by_alt_text", "getByAltText")
    locator_expr = locator_expr.replace("get_by_title", "getByTitle")
    locator_expr = locator_expr.replace("get_by_test_id", "getByTestId")
    locator_expr = locator_expr.replace("wait_for", "waitFor")

    if action == "click":
        lines.append(f"    await {locator_expr}.click();")
    elif action == "fill":
        lines.append(f"    await {locator_expr}.fill('{value}');")
    elif action == "select":
        lines.append(f"    await {locator_expr}.selectOption('{value}');")
    else:
        lines.append(f"    await {locator_expr}.click(); // action: {action}")

    # Insert Mendix async wait if needed
    if lr.get("needs_wait"):
        lines.append(f"    {MX_PROGRESS_WAIT.strip()}")

    return "\n".join(lines)


def _generate_assertion(expected_result: str) -> str:
    """Generate a final assertion block based on expected_result."""
    return (
        f"\n    // Assertion: {expected_result}\n"
        f"    await expect(page.getByText('{expected_result}')).toBeVisible({{ timeout: 15000 }});\n"
    )


def generate_test_code(
    test_case: dict,
    resolved_locators: list[dict],
    base_url: str,
) -> str:
    """Produce complete Playwright TypeScript test source code."""
    test_id       = str(test_case.get("id", "0"))
    test_title    = test_case.get("test_title", "unnamed_test")
    expected      = test_case.get("expected_result", "")

    safe_title = re.sub(r"[^a-zA-Z0-9]", "_", test_title).lower()

    step_lines = []
    for step in resolved_locators:
        step_lines.append(_generate_step_code(step))

    # Append assertion
    step_lines.append(_generate_assertion(expected))

    test_body = "\n".join(step_lines)

    code = TEST_FILE_TEMPLATE.format(
        test_id=test_id,
        test_title=test_title,
        csv_row_num=test_id,
        base_url=base_url,
        safe_title=safe_title,
        expected_result=expected,
        test_body=test_body,
    )

    # LLM refinement pass — clean up edge cases
    code = _llm_refine_code(code, test_title, expected)
    return code


def _llm_refine_code(raw_code: str, test_title: str, expected_result: str) -> str:
    """
    Optional LLM pass: let Gemini clean up the generated code,
    fix any obvious issues.
    """
    llm = _get_llm()
    prompt = f"""You are a Playwright TypeScript expert. Review and clean the following test script.
Rules:
- Keep all existing locator expressions exactly as-is.
- Ensure all Playwright actions are awaited.
- Fix any obvious syntax errors.
- Do NOT change locator selectors.
- Return ONLY the cleaned TypeScript code, no markdown fences.

```typescript
{raw_code}
```
"""
    try:
        response = llm.invoke([
            SystemMessage(content="You are a TypeScript test automation expert."),
            HumanMessage(content=prompt)
        ])
        cleaned = response.content.strip()
        if cleaned.startswith("```"):
            cleaned = cleaned.split("```")[1]
            if cleaned.startswith("typescript") or cleaned.startswith("javascript"):
                # strip language tag
                cleaned = re.sub(r"^(?:typescript|javascript|ts|js)\n", "", cleaned)
        return cleaned.strip()
    except Exception as exc:
        logger.warning(f"[Generator] LLM refinement failed: {exc}. Using raw code.")
        return raw_code


def run_generator_agent(state: dict) -> dict:
    """
    LangGraph node: Test Generator Agent.

    Reads resolved locators, generates a Playwright test file, writes
    it to generated_tests/, and stores the path in state.
    """
    test_case         = state.get("current_test", {})
    resolved_locators = state.get("resolved_locators", [])
    base_url          = state.get("base_url", "")

    logger.info(f"[Generator] Generating test: {test_case.get('test_title')}")

    code = generate_test_code(test_case, resolved_locators, base_url)

    file_path = write_test_file(
        test_id=str(test_case.get("id", "0")),
        test_title=test_case.get("test_title", "unnamed"),
        code=code,
    )

    logger.info(f"[Generator] Written → {file_path}")

    return {**state, "generated_file": file_path, "generated_code": code}
